language: java
jdk: oraclejdk9
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

services:
  postgresql

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: BroForce-02-2018
  on:
    repo: BatrSens/BroForce-02-2018
    branch: master
  skip_cleanup: true