language: java
jdk: oraclejdk9
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

addons:
  postgresql: "9.6"

services:
  - postgresql

before_install:
  - psql -c "create user vitalya with password '1324qwer';" -U postgres
  - psql -c "create database brodb;" -U postgres
  - psql -c "grant all on database brodb to vitalya;" -U postgres